### ISSUE TITLE
Bad UI visibility

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Rock-Paper-Scissors#1]
White bg and white text not that good contrast

<img width="563" alt="Screenshot 2023-04-07 at 8 16 25 PM" src="https://user-images.githubusercontent.com/74326345/230628484-74cff889-c1fb-4571-b8a3-ac9d522950dd.png">

**Comment by malivinayak** [comment]
@OutdatedGuy Check now

**Comment by OutdatedGuy** [comment]
Visible now in dark mode but now it loses the aesthetics of dark mode.

Can you try making it look like the below github theme. It is visible and also looks good in dark mode.

<img width="840" alt="Screenshot 2023-04-07 at 10 15 30 PM" src="https://user-images.githubusercontent.com/74326345/230645958-f04bf2c6-ee98-4713-9574-89296524e18a.png">

**Comment by malivinayak** [comment]
> Visible now in dark mode but now it loses the aesthetics of dark mode.
> 
> Can you try making it look like the below github theme. It is visible and also looks good in dark mode.
> 

Sure I will try

**Comment by malivinayak** [comment]
> Sure I will try
>

![image](https://user-images.githubusercontent.com/66154908/230652570-0d0cb41b-0228-4c5d-92ce-676e9b820b1e.png)

**Comment by OutdatedGuy** [comment]
Awesome 🤟🏼
