### ISSUE TITLE
Body not aligned with scrollbar

### ISSUE THREAD

**Issue by OutdatedGuy** [malivinayak/Rock-Paper-Scissors#2]
At max top scroll position, body is not aligned properly with scrollbar

<img width="579" alt="Screenshot 2023-04-07 at 8 19 32 PM" src="https://user-images.githubusercontent.com/74326345/230628888-30d74041-7d3f-466b-a0b8-b0b658acfc29.png">

**Comment by malivinayak** [comment]
Resolved [97d0e5c](https://github.com/malivinayak/Rock-Paper-Scissors/commit/97d0e5cbfac90498369c55a275b8832cadfc3b02)

**Comment by malivinayak** [comment]
Resolved at [97d0e5c](https://github.com/malivinayak/Rock-Paper-Scissors/commit/97d0e5cbfac90498369c55a275b8832cadfc3b02)
